FROM alpine as alpbase

WORKDIR /mutiny

ADD radamsa-v0.6.tar.gz .
RUN apk update && apk add \
    build-base \
    libxml2-dev \
    libxslt-dev \
    git \
    wget \
    curl
RUN (cd radamsa-0.6 && make)


FROM python:3.10-alpine

WORKDIR /mutiny

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY util/ util/
COPY backend/ backend/
COPY mutiny.py .
COPY mutiny_classes/ mutiny_classes/

COPY --from=alpbase /mutiny/radamsa-0.6 ./radamsa-0.6/

CMD ["/bin/ash"]
