FROM python:3.10

WORKDIR /mutiny

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY util/ util/
COPY backend/ backend/
COPY mutiny.py .
COPY mutiny_classes/ mutiny_classes/

ADD radamsa-v0.6.tar.gz .

RUN cd radamsa-0.6 && \
    make

CMD ["/bin/bash"]
