server:
  ip: 127.0.0.1
  port: 9876

agent:
  channel: 1
  minimal_mode: false
  type: 'remote-agent'

modules:
  - type: ProcessMonitor
    process_name: 'process_name_1'
    process_id: 20000
    time_interval: 1
    active: True
  - type: FileMonitor
    filename: 'file.log'
    f_regex: 'regex'
    time_interval: 1
    active: False
  - type: StatsMonitor
    process_name: 'process_name_2'
    process_id: 20000
    host: '127.0.0.1'
    time_interval: 1
    health_config:
      cpu_multiplier: 1.75
      ping_multiplier: 2.5
      memory_multiplier: 1.3
      disk_multiplier: 1.2
    active: True
